/* 
 * MovieGrep API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using apiProxy.proxyGeneratedCode.Client;
using apiProxy.proxyGeneratedCode.Model;
using Microsoft.Extensions.Options;

namespace apiProxy.proxyGeneratedCode.API
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITagApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns></returns>
        void AddTag (string version, AddTagRequest addTagRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddTagWithHttpInfo (string version, AddTagRequest addTagRequest = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns></returns>
        void AddTagToMedia (string mediaId, string version, List<string> tagIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddTagToMediaWithHttpInfo (string mediaId, string version, List<string> tagIds = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns></returns>
        void AddTextTag (string textId, string version, List<string> tagIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddTextTagWithHttpInfo (string textId, string version, List<string> tagIds = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddTagAsync (string version, AddTagRequest addTagRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddTagAsyncWithHttpInfo (string version, AddTagRequest addTagRequest = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddTagToMediaAsync (string mediaId, string version, List<string> tagIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddTagToMediaAsyncWithHttpInfo (string mediaId, string version, List<string> tagIds = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddTextTagAsync (string textId, string version, List<string> tagIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddTextTagAsyncWithHttpInfo (string textId, string version, List<string> tagIds = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TagApi : ITagApi
    {
        private apiProxy.proxyGeneratedCode.Client.ExceptionFactory _exceptionFactory = (name, response) => null;
        private ApiProxySetting _apiProxySetting;
        /// <summary>
        /// Initializes a new instance of the <see cref="TagApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TagApi(IOptions<ApiProxySetting> settingOptions)
        {
            _apiProxySetting = settingOptions.Value;
            this.Configuration = new apiProxy.proxyGeneratedCode.Client.Configuration { BasePath = _apiProxySetting.BaseUrl };

            ExceptionFactory = apiProxy.proxyGeneratedCode.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TagApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TagApi(apiProxy.proxyGeneratedCode.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = apiProxy.proxyGeneratedCode.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = apiProxy.proxyGeneratedCode.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public apiProxy.proxyGeneratedCode.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public apiProxy.proxyGeneratedCode.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns></returns>
        public void AddTag (string version, AddTagRequest addTagRequest = null)
        {
             AddTagWithHttpInfo(version, addTagRequest);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddTagWithHttpInfo (string version, AddTagRequest addTagRequest = null)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTag");

            var localVarPath = "/api/v{version}/Tag";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (addTagRequest != null && addTagRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(addTagRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = addTagRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTag", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddTagAsync (string version, AddTagRequest addTagRequest = null)
        {
             await AddTagAsyncWithHttpInfo(version, addTagRequest);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="addTagRequest"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddTagAsyncWithHttpInfo (string version, AddTagRequest addTagRequest = null)
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTag");

            var localVarPath = "/api/v{version}/Tag";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (addTagRequest != null && addTagRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(addTagRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = addTagRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTag", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns></returns>
        public void AddTagToMedia (string mediaId, string version, List<string> tagIds = null)
        {
             AddTagToMediaWithHttpInfo(mediaId, version, tagIds);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddTagToMediaWithHttpInfo (string mediaId, string version, List<string> tagIds = null)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
                throw new ApiException(400, "Missing required parameter 'mediaId' when calling TagApi->AddTagToMedia");
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTagToMedia");

            var localVarPath = "/api/v{version}/Tag/media/{mediaId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (mediaId != null) localVarPathParams.Add("mediaId", this.Configuration.ApiClient.ParameterToString(mediaId)); // path parameter
            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (tagIds != null && tagIds.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(tagIds); // http body (model) parameter
            }
            else
            {
                localVarPostBody = tagIds; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTagToMedia", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddTagToMediaAsync (string mediaId, string version, List<string> tagIds = null)
        {
             await AddTagToMediaAsyncWithHttpInfo(mediaId, version, tagIds);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mediaId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddTagToMediaAsyncWithHttpInfo (string mediaId, string version, List<string> tagIds = null)
        {
            // verify the required parameter 'mediaId' is set
            if (mediaId == null)
                throw new ApiException(400, "Missing required parameter 'mediaId' when calling TagApi->AddTagToMedia");
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTagToMedia");

            var localVarPath = "/api/v{version}/Tag/media/{mediaId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (mediaId != null) localVarPathParams.Add("mediaId", this.Configuration.ApiClient.ParameterToString(mediaId)); // path parameter
            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (tagIds != null && tagIds.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(tagIds); // http body (model) parameter
            }
            else
            {
                localVarPostBody = tagIds; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTagToMedia", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns></returns>
        public void AddTextTag (string textId, string version, List<string> tagIds = null)
        {
             AddTextTagWithHttpInfo(textId, version, tagIds);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddTextTagWithHttpInfo (string textId, string version, List<string> tagIds = null)
        {
            // verify the required parameter 'textId' is set
            if (textId == null)
                throw new ApiException(400, "Missing required parameter 'textId' when calling TagApi->AddTextTag");
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTextTag");

            var localVarPath = "/api/v{version}/Tag/text/{textId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (textId != null) localVarPathParams.Add("textId", this.Configuration.ApiClient.ParameterToString(textId)); // path parameter
            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (tagIds != null && tagIds.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(tagIds); // http body (model) parameter
            }
            else
            {
                localVarPostBody = tagIds; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTextTag", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddTextTagAsync (string textId, string version, List<string> tagIds = null)
        {
             await AddTextTagAsyncWithHttpInfo(textId, version, tagIds);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="apiProxy.proxyGeneratedCode.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="textId"></param>
        /// <param name="version"></param>
        /// <param name="tagIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddTextTagAsyncWithHttpInfo (string textId, string version, List<string> tagIds = null)
        {
            // verify the required parameter 'textId' is set
            if (textId == null)
                throw new ApiException(400, "Missing required parameter 'textId' when calling TagApi->AddTextTag");
            // verify the required parameter 'version' is set
            if (version == null)
                throw new ApiException(400, "Missing required parameter 'version' when calling TagApi->AddTextTag");

            var localVarPath = "/api/v{version}/Tag/text/{textId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (textId != null) localVarPathParams.Add("textId", this.Configuration.ApiClient.ParameterToString(textId)); // path parameter
            if (version != null) localVarPathParams.Add("version", this.Configuration.ApiClient.ParameterToString(version)); // path parameter
            if (tagIds != null && tagIds.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(tagIds); // http body (model) parameter
            }
            else
            {
                localVarPostBody = tagIds; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddTextTag", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
