/* 
 * MovieGrep API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = apiProxy.proxyGeneratedCode.Client.SwaggerDateConverter;

namespace apiProxy.proxyGeneratedCode.Model
{
    /// <summary>
    /// AddTagRequest
    /// </summary>
    [DataContract]
    public partial class AddTagRequest :  IEquatable<AddTagRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddTagRequest" /> class.
        /// </summary>
        /// <param name="tagText">tagText.</param>
        public AddTagRequest(string tagText = default(string))
        {
            this.TagText = tagText;
        }
        
        /// <summary>
        /// Gets or Sets TagText
        /// </summary>
        [DataMember(Name="tagText", EmitDefaultValue=false)]
        public string TagText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddTagRequest {\n");
            sb.Append("  TagText: ").Append(TagText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddTagRequest);
        }

        /// <summary>
        /// Returns true if AddTagRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddTagRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddTagRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TagText == input.TagText ||
                    (this.TagText != null &&
                    this.TagText.Equals(input.TagText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TagText != null)
                    hashCode = hashCode * 59 + this.TagText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
